name: CI
on: [pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v
      
    - name: Danger
      run: danger-swift ci
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
